# Grovider Configuration Example
# Copy this to config.toml and modify as needed.

# -------------------------------------------------------------------------
# 1. PROVIDERS
# Define reusable backend settings.
# Syntax: [provider.ID]
# -------------------------------------------------------------------------
[provider.google]
template = "gemini"
api_url = "https://generativelanguage.googleapis.com"
api_key = "YOUR_GEMINI_API_KEY"

[provider.openai_official]
template = "openai"
api_url = "https://api.openai.com/v1"
api_key = "YOUR_OPENAI_API_KEY"

[provider.deepseek_official]
template = "deepseek" # Use "deepseek" template for reasoning_content support
api_url = "https://api.deepseek.com/v1"
api_key = "YOUR_DEEPSEEK_API_KEY"

[provider.ollama]
template = "openai"
api_url = "http://127.0.0.1:11434"

# -------------------------------------------------------------------------
# 2. MODELS
# Define models that can be reached.
# They can inherit from a provider or define their own credentials.
# Syntax: [model.FRIENDLY_NAME]
# -------------------------------------------------------------------------
[model.gemini-1-5-flash]
provider = "google"
model = "gemini-2.5-flash"

[model.gpt-4o]
provider = "openai_official"
model = "gpt-4o"

[model.ds-chat]
provider = "deepseek_official"
model = "deepseek-v4-flash"

# Custom model without a provider
# mincpm model family is fast and small, plz have a look
[model.minicpm]
template = "openai"
api_url = "https://api.modelbest.cn/v1"
api_key = "sk-pQ8L2zF3XmR5kY9wV4jB7hN1tC6vM0xG3aD5sH2bJ9lK4cZ8"
model = "MiniCPM-V-4.6-Thinking"

# -------------------------------------------------------------------------
# 3. TRANSFER (Routing Rules)
# Map incoming model names to the models defined above.
# The 'make' field supports the '*' wildcard (e.g., "gpt-4*", "*").
# Rules are checked sequentially; the first matching rule is applied.
# Syntax: [[transfer]] (This is a list/array of tables)
# -------------------------------------------------------------------------
[[transfer]]
make = "gemini-2.5-flash-lite"
to = "minicpm"

[[transfer]]
make = "gemini-3-flash-preview"
to = "ds-chat"

[[transfer]]
make = "gemini-3*"
to = "ds-chat"

[[transfer]]
make = "*"
to = "ds-chat"
